# This formula is auto-generated by the GitHub Actions release workflow.
# Do not edit by hand — edit homebrew/accelerate-guru.rb in the source repo.
#
# Tap:     brew tap accelerate-guru/tap
# Install: brew install accelerate-guru
# Service: brew services start accelerate-guru

class AccelerateGuru < Formula
  desc "Ultra-high performance intelligent reverse proxy for Magento 2"
  homepage "https://accelerator.guru"
  # version, url, and sha256 are replaced automatically on every release
  version "0.1.0"
  license "Proprietary"

  on_macos do
    on_arm do
      url "https://accelerator.guru/dist/v0.1.0/accelerate-guru-darwin-aarch64.tar.gz"
      sha256 "851dbbe60f88ed59e3955180db03013176e77fb4edcc203f5fc6b4ebf7aa966b"
    end

    on_intel do
      url "https://accelerator.guru/dist/v0.1.0/accelerate-guru-darwin-x86_64.tar.gz"
      sha256 "af8feebf868cb25bcd28f3ddef2b6ec96657818a8315b4803941935db5b27f5e"
    end
  end

  def install
    bin.install "accelerate-guru"
    # Create the default config directory so the service has a home.
    (etc/"accelerate-guru").mkpath
  end

  # `brew services start accelerate-guru` registers a launchd plist and starts
  # the proxy automatically on login. Edit the config file first:
  #   $HOMEBREW_PREFIX/etc/accelerate-guru/magento_ultra.ini
  service do
    run           [opt_bin/"accelerate-guru", "--from-dir", etc/"accelerate-guru"]
    working_dir   etc/"accelerate-guru"
    keep_alive    true
    log_path      var/"log/accelerate-guru.log"
    error_log_path var/"log/accelerate-guru-error.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/accelerate-guru --version")
  end
end
