# This formula is auto-generated by the GitHub Actions release workflow.
# Do not edit by hand — edit homebrew/accelerate-guru.rb in the source repo.
#
# Tap:     brew tap accelerate-guru/tap
# Install: brew install accelerate-guru
# Service: brew services start accelerate-guru

class AccelerateGuru < Formula
  desc "Ultra-high performance intelligent reverse proxy for Magento 2"
  homepage "https://accelerate.guru"
  # version, url, and sha256 are replaced automatically on every release
  version "0.3.0"
  license "Proprietary"

  on_macos do
    on_arm do
      url "https://accelerate.guru/dist/v0.3.0/accelerate-guru-darwin-aarch64.tar.gz"
      sha256 "46e023b705a1f5f1624322f18f680cd5f857dc6a4d64b6a2c0f1209b72957356"
    end

    on_intel do
      url "https://accelerate.guru/dist/v0.3.0/accelerate-guru-darwin-x86_64.tar.gz"
      sha256 "6ea78bc25061a22c8771d5bfb2faead209f1ea970c537c2cf3c177383502bb5e"
    end
  end

  def install
    bin.install "accelerate-guru"
    # Create the default config directory so the service has a home.
    (etc/"accelerate-guru").mkpath
  end

  # `brew services start accelerate-guru` registers a launchd plist and starts
  # the proxy automatically on login. Edit the config file first:
  #   $HOMEBREW_PREFIX/etc/accelerate-guru/magento_ultra.ini
  service do
    run           [opt_bin/"accelerate-guru", "--from-dir", etc/"accelerate-guru"]
    working_dir   etc/"accelerate-guru"
    keep_alive    true
    log_path      var/"log/accelerate-guru.log"
    error_log_path var/"log/accelerate-guru-error.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/accelerate-guru --version")
  end
end
